# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 이로운
title: Backend Engineer
email: dev.rowoon@gmail.com
# email_title: Email (Email title override)
phone: 01025927128
# phone_title: Phone (Phone title override)
website: https://codebene.tistory.com/
website_title: Blog

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
github_username: rowooncoding
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

#Additional icon links
additional_links:
  - title: portfolio
    #icon: fab fa-twitter
    icon: fas fa-file-powerpoint
    url: https://www.miricanvas.com/v/12twf7x

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/증명사진.jpg
# Directory of profile image (eg. images/profile.jpg) 
about_content: | # 자기소개 적으면 됨
  `로운스쿨을 통한 이로운 개발자라는 꿈`: <b>로운스쿨<b>이라는 스터디를 만들어 제가 쌓아온 지식을 정리하고 <b>20명의 스터디원에게 강의를 진행해오고 있습니다.<b>
  또한, 각 프로젝트에서 리더 역할을 수행하면서 다양한 인간성을 이해하고 경험하였습니다. 이를 바탕으로 <b>원활한 커뮤니케이션과 효과적인 협업을 가능케 하는 능력<b>을 키워왔습니다.
  
  `고객이 필요로 하는` 서비스를 개발하는 것이 중요하다는 생각에 사용자의 경험, 서비스 사용성 등에 대해서도 함께 고민하며 개발을 공부하고 있습니다.
  
  1년간 백엔드와 프론트엔드 기술을 익혀 갓생만들기 프로젝트, 혼밥매칭 서비스를 팀장으로서 기획하고 개발하였습니다. 이러한 풀스택 프로젝트를 진행하면서 백엔드와 프론트엔드 개발에 대한 지식을 함께 쌓아왔습니다.
  
  깃허브와 블로그를 적극 활용하여 <b>문서화<b>를 진행하고 기록합니다.

content:
#  - title: Work Experience
#    layout: list
#    content:
#      - layout: left
#        title: Company name
#        sub_title: Backend Engineer
#        caption: 2024.01.01
#        link: Link to company (optional)
#        quote: >
#          Short description of the company (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of role
  - title: 역량
    layout: list
    content:
      - layout: top-left
        title: 서비스 개발
        sub_title: 신규 서비스 개발
        description: | # 해당하는 기술 블로그가 있다면 링크 걸어두기 pw포함해서
         - [2023-11 ~ 2023-11, 청년취업사관학교 파이널 프로젝트] 카카오 지도 api를 사용한 약속만들기 서비스 개발
         - [2023-11 ~ 2023-11, 청년취업사관학교 파이널 프로젝트] 카카오 지도 api를 사용한 메인페이지 개발(게시글 동적 랜더링) 
         - [2023-11 ~ 2023-11, 청년취업사관학교 파이널 프로젝트] React와 Spring Boot를 분리한 개발환경 구축 
         - [2023-11 ~ 2023-11, 청년취업사관학교 파이널 프로젝트] MySQL을 사용한 게시글 부분 데이터베이스 구축 
         - [2023-03 ~ 2023-04, 멋쟁이 사자처럼 파이널 프로젝트] 글쓰기 서비스 개발
         - [2023-03 ~ 2023-04, 멋쟁이 사자처럼 파이널 프로젝트] Firebase를 사용한 데이터베이스 관리
         - [2023-03 ~ 2023-04, 멋쟁이 사자처럼 파이널 프로젝트] github actions, pages 활용한 CI/CD 환경 구축- layout: top-left

      - layout: top-left
        title: 시스템 기획 및 설계
        sub_title: 신규 서비스 개발
        description: | # 해당하는 기술 블로그가 있다면 링크 걸어두기 pw포함해서
         - [청년취업사관학교 파이널 프로젝트, 멋쟁이 사자처럼] 최근 뉴스를 확인하고 니즈 파악 및 주제선정
         - [청년취업사관학교 파이널 프로젝트, 멋쟁이 사자처럼] 피그마를 사용한 와이어프레임, 디자인 생성
         - [청년취업사관학교 파이널 프로젝트, 멋쟁이 사자처럼] 프로젝트 아키텍쳐 설계 및 명세서 작성
  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
        # other value (or no value) means no border will be displayed
        title: 혼밥멈춰
#        link: https://github.com/youngboyclub/honbab-mumcha
#        link_text: 프로젝트 깃허브
        additional_links:
          - title: 백엔드 Repo
            icon: fab fa-github
            url: https://github.com/youngboyclub/honbab-mumcha
          - title: 프론트엔드 Repo
            icon: fab fa-github
            url: https://github.com/youngboyclub/honbab-mumcha-front-
        quote: >
          더 이상 혼밥하지 말자구요!
        description: | # this will include new lines to allow paragraphs
          - 피그마 활용한 와이어프레임, 디자인
          - 기술스택, 라이브러리 선정을 위한 회의 주도
          - `리액트`, `스프링부트`를 연동하여 개발환경 구축
          - 컬렉션 변경, 타입 변경으로 MyPage 성능 향상
          - 카카오 지도 api 공식 코드를 리액트 코드로 수정 후 사용
          - `카카오 지도 api`를 사용하여 약속 생성 페이지 완성
          - `카카오 지도 api`를 사용하여 메인페이지 완성
          - 데이터 일관성 유지를 위하여 `base 엔티티` 사용
          - 협업 경험을 위한 `Swagger` 라이브러리 사용
          - `axios`를 사용하여 비동기 통신
          - `Restful API`를 지향한 API 구축
          - 회의록 및 프로젝트 구조 <b>문서화</b>
          - 피피티 활용하여 데모데이 발표 진행
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
        # other value (or no value) means no border will be displayed
        title: God Life
        #        link: https://github.com/youngboyclub/honbab-mumcha
        #        link_text: 프로젝트 깃허브
        additional_links:
          - title: 갓생 깃허브 주소
            icon: fab fa-github
            url: https://github.com/likelion-lab10/godlife
        quote: >
          개발자의 건강을 위해서 우리모두 갓생!
        description: | # this will include new lines to allow paragraphs
          - 피그마 활용한 와이어프레임, 디자인
          - 기술스택, 라이브러리 선정을 위한 회의 주도
          - `리액트`와 `fireabase`, `tailwind`의 개발환경 구축
          - 공통 컴포넌트 생성
          - `firebase` 데이터베이스 관리
          - 챌린지 작성 페이지를 구축하여 해쉬태그, 사진파일, 카테고리 등을 데이터베이스에 저장
          - Sweet Alert2 라이브러리 사용
          - github action, pages 활용하여 <b>CI/CD 환경 구축<b>
          - 회의록 및 프로젝트 구조 <b>문서화<b>
          - 피피티 활용하여 데모데이 발표 진행
  - title: 기술스택
    layout: list
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java
          - Spring Boot
          - Spring Data JPA
          - Junit5
          - Gradle
          - IntelliJ
      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          - Html
          - CSS
          - React
          - Tailwind
          - Visual Studio Code
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - MySQL
          - Vercel, GitHub Action
          - Git
  - title: 학력
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2016-03 ~  2022-02, 순천향대학교] 경제금융학 학사
      - [2014-03 ~  2016-02, 매탄고등학교] 졸업
  - title: 활동 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
        # other value (or no value) means no border will be displayed
        title: 백엔드 개발자 과정(JAVA 기반)
        quote: >
          청년취업사관학교(SESAC)
        description: | # this will include new lines to allow paragraphs
          - 자바 문법에 대한 학습과 순수 자바를 활용한 토이프로젝트 경험
          - 오라클 현업자에게 배우는 오라클 데이터베이스 쿼리문 학습
          - 자바 현업자에게 배우는 스프링부트 기본(DI, IoC)
          - 펫 인포 토이프로젝트로 배우는 스프링 부트 MVC 모델링
          - AWS를 활용한 CI/CD 환경 구축 및 클라우드 활용법 학습
          - 풀스택 프로젝트 진행
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
        # other value (or no value) means no border will be displayed
        title: 프론트엔드 스쿨 4기
        quote: >
          멋쟁이 사자처럼 X 이듬
        description: | # this will include new lines to allow paragraphs
          - 고정형, 반응형 웹 학습
          - 접근성에 대한 학습
          - 사용자 중심 UI/UX 설계방법 학습
          - React를 사용한 미니 프로젝트 만들기
          - VITE를 사용한 라이브러리 환경설정과 빌드 학습
          - Git/GitHub 세팅법과 사용 연습
          - 리액트와 firebase를 활용한 파이널프로젝트
  - title: 수상
    layout: list
    content:
      - layout: top-left
        title: 청년취업사관학교(Sesac)
        sub_title: 파이널프로젝트
        description: | # 해당하는 기술 블로그가 있다면 링크 걸어두기 pw포함해서
          - [2023-11 ~ 2023-11, 청년취업사관학교 파이널프로젝트] 베스트 팀워크상
      - layout: top-left
        title: 멋쟁이 사자처럼 프론트엔드 스쿨 4기
        sub_title: 수료식 Award
        description: | # 해당하는 기술 블로그가 있다면 링크 걸어두기 pw포함해서
          - [2023-04 ~ 2023-04, 멋쟁이 사자처럼] 컨텐츠상
          - [2023-04 ~ 2023-04, 멋쟁이 사자처럼] 동료 칭찬상 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
